"""Initial migration

Revision ID: 91eb2b47291c
Revises: 
Create Date: 2023-08-12 00:12:14.641598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eb2b47291c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
